/*
 * This source file was generated by the Gradle 'init' task
 */

import java.util.Scanner;

public class App {
    public String getGreeting() {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter your name: ");
        String name = scanner.nextLine();
        return "Hello, " + name + "!";
    }

    public String getAge() {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter your age: ");
        int age = scanner.nextInt();
        age += 100;
        return "Hello, you will be this old " + age + " after a 100 years";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().getAge());
    }
}
