/*
 * This source file was generated by the Gradle 'init' task
 */

import java.util.Scanner;

public class App {
    private final Scanner scanner;

    public App() {
        this.scanner = new Scanner(System.in);
    }

    public String getGreeting() {
        System.out.print("Enter your name: ");
        String name = scanner.nextLine();
        return "Hello, " + name + "!";
    }

    public String getAge() {
        System.out.print("Enter your age: ");
        int age = scanner.nextInt();
        return "Hello, you will be this old " + (age + 100) + " after a 100 years";
    }

    public String magicNumber() {
        System.out.print("Enter a number: ");
        int number = scanner.nextInt();
        int magic = calculateMagicNumber(number);
        return "Your magic number is: " + magic;
    }

    private int calculateMagicNumber(int number) {
        int magic = number * 6 / 2 + 7 - 3 * 2 + 1;
        magic = Math.abs(magic);
        magic = Math.min(100, Math.max(10, magic));
        return magic == 42 ? 0 : (magic == 0 ? 42 : magic);
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.getGreeting());
        System.out.println(app.getAge());
        System.out.println(app.magicNumber());
    }
}
